apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: esm7ikxa9-nodejs
  janus-idp.io/tekton: esm7ikxa9-nodejs
  backstage.io/kubernetes-id: esm7ikxa9-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: esm7ikxa9-nodejs
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
